[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
account_address_program = "PAJaDhENqtjWP8chUXGAoU6K9dsuKC65GdqwKTy5fgM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/Documents/june-17/FJe9GCMxy5LqhHvRauuNE1TJNsMwSTXMb5yWZGxjg6AM.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
